// <auto-generated />
using System;
using Identity.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Identity.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230722094210_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Identity.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b94bcae7-72ca-4f5a-986e-9da2c1ce3326"),
                            Age = 31,
                            Name = "Steward Blaszczynski",
                            Position = "Quality Control Specialist"
                        },
                        new
                        {
                            Id = new Guid("4a26a426-963b-43f3-b517-8f38e39c697f"),
                            Age = 27,
                            Name = "Colleen Bosence",
                            Position = "Accountant III"
                        },
                        new
                        {
                            Id = new Guid("085fbdc5-6c50-4ca9-a846-71e96e7cf04b"),
                            Age = 21,
                            Name = "Valenka Wiggett",
                            Position = "Senior Developer"
                        },
                        new
                        {
                            Id = new Guid("88b52515-eb9e-4f1b-8915-93fd1cae7140"),
                            Age = 31,
                            Name = "Sigismundo McClarence",
                            Position = "Structural Engineer"
                        },
                        new
                        {
                            Id = new Guid("19a9e271-55d3-4e28-a408-90fc9bf70fb5"),
                            Age = 29,
                            Name = "Gene Kenefick",
                            Position = "Marketing Manager"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
